site:
  title: "Antora Documentation Preview"
  url: http://localhost:2020/
  start_page: COMPONENT_NAME::index.adoc
content:
  sources:
  - url: /antora
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: ANTORA_PATH
ui:
  bundle:
    url: ANTORA_UI_BUNDLE
    snapshot: false
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: /preview/public
    clean: true
