= Antora Preview Tool

This tool can be used to quickly preview an Antora documentation website.

The image is available in https://hub.docker.com/r/vshn/antora-preview[Docker Hub].

== How to use

Run the following command on top of any project containing Antora documentation:

`docker run --rm --publish 35729:35729 --publish 2020:2020 --volume "${PWD}":/preview/antora vshn/antora-preview:2.3.4 --antora=docs --style=appuio`

Passing the `--help` parameter shows the inline help:

```
Antora Documentation Previewer

This command builds an Antora documentation website locally
and launches a web server on port 2020 to browse the documentation.

Arguments:
    --style=STYLE / -s=STYLE:
           Antora UI Bundle to use to render the documentation.
           Valid values: 'vshn', 'appuio', 'syn', 'antora'.
           Default value: 'vshn'

    -a=PATH / --antora=PATH:
           Path to the subfolder.
           Default: 'docs'

Examples:
    antora-preview --style=appuio --antora=src
```

Open the URL http://localhost:2020 to browse the documentation.

== LiveReload

This image is capable of "live reloading" the documention as the user writes the Asciidoc source. To do that, you need a browser with one of these extensions:

* https://addons.mozilla.org/en-US/firefox/addon/livereload-web-extension/[Firefox]
* https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei[Google Chrome]

Open the documentation in your browser and, in the case of Firefox, click on the LiveReload extension button on the toolbar; when it becomes green, the browser will automatically refresh whenever you save an Asciidoc file.
